-- PostgreSQL: one atomic statement. Requires an existing users.id = 1.
-- Design: Ivory paper, left-aligned serif masthead, burgundy rules, and dates aligned opposite role titles.
-- All profile details, organizations, and accomplishments are fictional.
-- Each execution creates a new resume; IDs are generated by the database.
WITH
content AS (
    SELECT $resume_data$
[
{"label": "Header", "type": "header", "columnPosition": 0, "showHeading": false, "styling": {"border": {"bottom": {"display": true, "width": "86%", "height": "2px", "style": "solid", "color": "#762F45"}}}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "HEADER", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#762F45"}]}], "subsections": [{"label": "Jane Doe", "fields": [{"label": "Name", "value": [{"type": "paragraph", "label": "Name", "children": [{"text": "Jane Doe", "fontSizeOffset": 23, "lineHeightOffset": 0, "bold": true, "color": "#762F45"}]}], "layout": {}}, {"label": "Title", "value": [{"type": "paragraph", "label": "Title", "children": [{"text": "DIRECTOR OF PEOPLE OPERATIONS", "fontSizeOffset": 0, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Contact", "value": [{"type": "paragraph", "label": "Contact", "children": [{"text": "Minneapolis, MN | (612) 555-0189 | jane.doe@example.com", "fontSizeOffset": -0.5, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Leadership Profile", "type": "summary", "columnPosition": 0, "showHeading": true, "styling": {}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "LEADERSHIP PROFILE", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#762F45"}]}], "subsections": [{"label": "Profile", "fields": [{"label": "Summary", "value": [{"type": "paragraph", "label": "Summary", "children": [{"text": "People operations leader with 10 years of experience building thoughtful employee programs for growing organizations. Aligns systems, manager support, and clear communication to create consistent employee experiences.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Career", "type": "workHistory", "columnPosition": 0, "showHeading": true, "styling": {}, "layout": {"display": "grid", "grid": {"columns": 2}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "CAREER", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#762F45"}]}], "subsections": [{"label": "Willow Bend Group", "fields": [{"label": "Job Title", "value": [{"type": "paragraph", "label": "Job Title", "children": [{"text": "Director of People Operations", "fontSizeOffset": 1, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Dates", "value": [{"type": "paragraph", "label": "Dates", "children": [{"text": "2022 - Present", "fontSizeOffset": -0.5, "lineHeightOffset": 0, "color": "#762F45"}], "textAlign": "right"}], "layout": {}}, {"label": "Company", "value": [{"type": "paragraph", "label": "Company", "children": [{"text": "Willow Bend Group", "fontSizeOffset": 0, "lineHeightOffset": 0, "bold": true}]}], "layout": {"startNewRow": true, "grid": {"fillRow": true}}}, {"label": "Description", "value": [{"type": "unordered-list", "children": [{"type": "list-item", "children": [{"text": "Led a 6-person team supporting 420 employees across 4 locations.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}, {"type": "list-item", "children": [{"text": "Rebuilt onboarding and manager support programs, improving new-hire satisfaction from 4.0 to 4.7 out of 5.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}, {"type": "list-item", "children": [{"text": "Introduced workforce dashboards that cut monthly reporting time by 40%.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}]}], "layout": {"startNewRow": true, "grid": {"fillRow": true}}}]}, {"label": "Maple Row Services", "fields": [{"label": "Job Title", "value": [{"type": "paragraph", "label": "Job Title", "children": [{"text": "People Operations Manager", "fontSizeOffset": 1, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Dates", "value": [{"type": "paragraph", "label": "Dates", "children": [{"text": "2016 - 2022", "fontSizeOffset": -0.5, "lineHeightOffset": 0, "color": "#762F45"}], "textAlign": "right"}], "layout": {}}, {"label": "Company", "value": [{"type": "paragraph", "label": "Company", "children": [{"text": "Maple Row Services", "fontSizeOffset": 0, "lineHeightOffset": 0, "bold": true}]}], "layout": {"startNewRow": true, "grid": {"fillRow": true}}}, {"label": "Description", "value": [{"type": "unordered-list", "children": [{"type": "list-item", "children": [{"text": "Built a shared employee service process that reduced response times by 35%.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}, {"type": "list-item", "children": [{"text": "Coordinated a performance review program with 98% on-time completion.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}]}], "layout": {"startNewRow": true, "grid": {"fillRow": true}}}]}]},
{"label": "Signature Program", "type": "projects", "columnPosition": 0, "showHeading": true, "styling": {"border": {"bottom": {"display": true, "width": "86%", "height": "1px", "style": "solid", "color": "#D8C5B7"}}}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "SIGNATURE PROGRAM", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#762F45"}]}], "subsections": [{"label": "Manager Program", "fields": [{"label": "Project Title", "value": [{"type": "paragraph", "label": "Project Title", "children": [{"text": "First-Time Manager Development", "fontSizeOffset": 1, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Description", "value": [{"type": "paragraph", "label": "Description", "children": [{"text": "Launched a practical learning series for 35 new managers, pairing guided workshops with peer coaching. Improved participant confidence scores by 29% after the first cohort.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Leadership Capabilities", "type": "skills", "columnPosition": 0, "showHeading": true, "styling": {}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "LEADERSHIP CAPABILITIES", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#762F45"}]}], "subsections": [{"label": "Capabilities", "fields": [{"label": "Strategy", "value": [{"type": "paragraph", "label": "Strategy", "children": [{"text": "People strategy / Workforce planning", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Programs", "value": [{"type": "paragraph", "label": "Programs", "children": [{"text": "Manager development / Employee experience", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Systems", "value": [{"type": "paragraph", "label": "Systems", "children": [{"text": "HR systems / Reporting / Process improvement", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Education", "type": "education", "columnPosition": 0, "showHeading": true, "styling": {}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "EDUCATION", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#762F45"}]}], "subsections": [{"label": "College", "fields": [{"label": "Degree", "value": [{"type": "paragraph", "label": "Degree", "children": [{"text": "B.A. Organizational Studies", "fontSizeOffset": 1, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "School", "value": [{"type": "paragraph", "label": "School", "children": [{"text": "Northlake College | 2012 - 2016", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}]}]}
]
$resume_data$::jsonb AS sections
),
new_resume AS (
    INSERT INTO resumes (user_id, title, styling, layout, created_at, updated_at)
    VALUES (
        1,
        'Jane Doe - Burgundy Executive',
        '{"display": "flex", "fontFamily": "Georgia, Times New Roman, serif", "fontSize": "11.5px", "lineHeight": 1.3, "color": "#30343B", "backgroundColor": "#FFFCF6"}'::json,
        '{"padding": {"top": "1.8rem", "right": "1.8rem", "bottom": "1.8rem", "left": "1.8rem"}, "gap": {"horizontal": "0.3rem", "vertical": "0.4rem", "subsection": "0.6rem", "field": "0.14rem"}}'::json,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
    RETURNING id, title
),
new_columns AS (
    INSERT INTO columns (resume_id, position, styling, layout, created_at, updated_at)
    SELECT r.id, c.position, '{}'::json, c.layout,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM new_resume r
    CROSS JOIN (VALUES
        (0, '{"width": {"auto": false, "value": "100%"}, "padding": {"top": "0rem", "bottom": "0rem", "left": "0.8rem", "right": "0.8rem"}}'::json)
    ) AS c(position, layout)
    RETURNING id, position
),
section_data AS (
    SELECT (s.ordinality - 1)::integer AS position, s.item
    FROM content
    CROSS JOIN LATERAL jsonb_array_elements(content.sections)
        WITH ORDINALITY AS s(item, ordinality)
),
new_sections AS (
    INSERT INTO sections (
        column_id, label, type, value, show_heading, position,
        styling, layout, created_at, updated_at
    )
    SELECT c.id, s.item->>'label', s.item->>'type',
        (s.item->'value')::json,
        (s.item->>'showHeading')::boolean, s.position,
        (s.item->'styling')::json, (s.item->'layout')::json,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM section_data s
    JOIN new_columns c ON c.position = (s.item->>'columnPosition')::integer
    RETURNING id, position
),
subsection_data AS (
    SELECT s.id AS section_id, (sub.ordinality - 1)::integer AS position, sub.item
    FROM new_sections s
    JOIN section_data d ON d.position = s.position
    CROSS JOIN LATERAL jsonb_array_elements(d.item->'subsections')
        WITH ORDINALITY AS sub(item, ordinality)
),
new_subsections AS (
    INSERT INTO subsections (
        section_id, label, type, position, styling, layout, created_at, updated_at
    )
    SELECT d.section_id, d.item->>'label', s.item->>'type', d.position,
        '{"fontSizeOffset":0,"lineHeightOffset":0}'::json, '{}'::json,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM subsection_data d
    JOIN new_sections n ON n.id = d.section_id
    JOIN section_data s ON s.position = n.position
    RETURNING id, section_id, position
),
new_fields AS (
    INSERT INTO fields (
        subsection_id, label, value, position, styling, layout, created_at, updated_at
    )
    SELECT sub.id, f.item->>'label', (f.item->'value')::json,
        (f.ordinality - 1)::integer,
        '{"fontSizeOffset":0,"lineHeightOffset":0}'::json, COALESCE((f.item->'layout')::json, '{}'::json),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM new_subsections sub
    JOIN subsection_data d ON d.section_id = sub.section_id AND d.position = sub.position
    CROSS JOIN LATERAL jsonb_array_elements(d.item->'fields')
        WITH ORDINALITY AS f(item, ordinality)
    RETURNING id
)
SELECT id AS resume_id, title, (SELECT count(*) FROM new_fields) AS fields_created
FROM new_resume;
