-- PostgreSQL: one atomic statement. Requires an existing users.id = 1.
-- Design: White identity rail with stacked name and a continuous copper divider; wide technical narrative.
-- All profile details, organizations, and accomplishments are fictional.
-- Each execution creates a new resume; IDs are generated by the database.
WITH
content AS (
    SELECT $resume_data$
[
{"label": "Identity", "type": "header", "columnPosition": 0, "showHeading": false, "styling": {"border": {"right": {"display": true, "width": "2px", "height": "100%", "style": "solid", "color": "#BA571B"}}}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "IDENTITY", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#BA571B"}]}], "subsections": [{"label": "John Doe", "fields": [{"label": "First Name", "value": [{"type": "paragraph", "label": "First Name", "children": [{"text": "JOHN", "fontSizeOffset": 15, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Last Name", "value": [{"type": "paragraph", "label": "Last Name", "children": [{"text": "DOE", "fontSizeOffset": 24, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Role", "value": [{"type": "paragraph", "label": "Role", "children": [{"text": "PROJECT ENGINEER", "fontSizeOffset": 0, "lineHeightOffset": 0, "bold": true, "color": "#BA571B"}]}], "layout": {}}]}]},
{"label": "Contact", "type": "contact", "columnPosition": 0, "showHeading": true, "styling": {"border": {"right": {"display": true, "width": "2px", "height": "100%", "style": "solid", "color": "#BA571B"}}}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "CONTACT", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#BA571B"}]}], "subsections": [{"label": "Contact", "fields": [{"label": "Location", "value": [{"type": "paragraph", "label": "Location", "children": [{"text": "Columbus, OH", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Phone", "value": [{"type": "paragraph", "label": "Phone", "children": [{"text": "(614) 555-0153", "fontSizeOffset": -0.5, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Email", "value": [{"type": "paragraph", "label": "Email", "children": [{"text": "john.doe@example.com", "fontSizeOffset": -1, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Expertise", "type": "skills", "columnPosition": 0, "showHeading": true, "styling": {"border": {"right": {"display": true, "width": "2px", "height": "100%", "style": "solid", "color": "#BA571B"}}}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "EXPERTISE", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#BA571B"}]}], "subsections": [{"label": "Skills", "fields": [{"label": "Planning", "value": [{"type": "paragraph", "label": "Planning", "children": [{"text": "Project planning", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Quality", "value": [{"type": "paragraph", "label": "Quality", "children": [{"text": "Quality control", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Vendors", "value": [{"type": "paragraph", "label": "Vendors", "children": [{"text": "Vendor coordination", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Risk", "value": [{"type": "paragraph", "label": "Risk", "children": [{"text": "Risk tracking", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Tools", "value": [{"type": "paragraph", "label": "Tools", "children": [{"text": "CAD / Excel / MS Project", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Education", "type": "education", "columnPosition": 0, "showHeading": true, "styling": {"border": {"right": {"display": true, "width": "2px", "height": "100%", "style": "solid", "color": "#BA571B"}}}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "EDUCATION", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#BA571B"}]}], "subsections": [{"label": "College", "fields": [{"label": "Degree", "value": [{"type": "paragraph", "label": "Degree", "children": [{"text": "B.S. Mechanical Engineering", "fontSizeOffset": 0, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "School", "value": [{"type": "paragraph", "label": "School", "children": [{"text": "Lakecrest College", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}, {"label": "Dates", "value": [{"type": "paragraph", "label": "Dates", "children": [{"text": "2014 - 2018", "fontSizeOffset": -0.5, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Engineering Profile", "type": "summary", "columnPosition": 1, "showHeading": true, "styling": {}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "ENGINEERING PROFILE", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#BA571B"}]}], "subsections": [{"label": "Profile", "fields": [{"label": "Summary", "value": [{"type": "paragraph", "label": "Summary", "children": [{"text": "Project engineer with 8 years of experience coordinating equipment upgrades and production improvements. Brings a structured approach to scope, schedules, and communication across technical teams.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Experience", "type": "workHistory", "columnPosition": 1, "showHeading": true, "styling": {}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "EXPERIENCE", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#BA571B"}]}], "subsections": [{"label": "Copperline Manufacturing", "fields": [{"label": "Job Title", "value": [{"type": "paragraph", "label": "Job Title", "children": [{"text": "Project Engineer", "fontSizeOffset": 1, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Company", "value": [{"type": "paragraph", "label": "Company", "children": [{"text": "Copperline Manufacturing | 2022 - Present", "fontSizeOffset": -0.5, "lineHeightOffset": 0, "color": "#606873"}]}], "layout": {}}, {"label": "Description", "value": [{"type": "unordered-list", "children": [{"type": "list-item", "children": [{"text": "Coordinated 7 equipment upgrade projects with a combined budget of $1.8M.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}, {"type": "list-item", "children": [{"text": "Improved change tracking and reduced schedule overruns by 24%.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}, {"type": "list-item", "children": [{"text": "Worked with maintenance teams to cut planned installation downtime by 18%.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}]}], "layout": {}}]}, {"label": "Atlas Reed Industries", "fields": [{"label": "Job Title", "value": [{"type": "paragraph", "label": "Job Title", "children": [{"text": "Mechanical Engineer", "fontSizeOffset": 1, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Company", "value": [{"type": "paragraph", "label": "Company", "children": [{"text": "Atlas Reed Industries | 2018 - 2022", "fontSizeOffset": -0.5, "lineHeightOffset": 0, "color": "#606873"}]}], "layout": {}}, {"label": "Description", "value": [{"type": "unordered-list", "children": [{"type": "list-item", "children": [{"text": "Designed fixtures that reduced assembly setup time by 20%.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}, {"type": "list-item", "children": [{"text": "Maintained technical drawings and supported supplier reviews for 15 components.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}, {"type": "list-item", "children": [{"text": "Documented acceptance checks to improve handoffs between engineering and production.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}]}], "layout": {}}]}]},
{"label": "Selected Delivery", "type": "projects", "columnPosition": 1, "showHeading": true, "styling": {}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "SELECTED DELIVERY", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#BA571B"}]}], "subsections": [{"label": "Line Upgrade", "fields": [{"label": "Project Title", "value": [{"type": "paragraph", "label": "Project Title", "children": [{"text": "Assembly Line Modernization", "fontSizeOffset": 1, "lineHeightOffset": 0, "bold": true}]}], "layout": {}}, {"label": "Description", "value": [{"type": "paragraph", "label": "Description", "children": [{"text": "Coordinated design reviews, vendor milestones, and installation planning for a new assembly cell. Completed the launch within budget and increased throughput by 17%.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}]}]},
{"label": "Working Style", "type": "custom", "columnPosition": 1, "showHeading": true, "styling": {}, "layout": {"display": "grid", "grid": {"columns": 1}, "padding": {"top": "0rem", "bottom": "0rem"}}, "value": [{"type": "heading", "textAlign": "left", "children": [{"text": "WORKING STYLE", "bold": true, "fontSizeOffset": 0, "lineHeightOffset": 0, "color": "#BA571B"}]}], "subsections": [{"label": "Working Style", "fields": [{"label": "Description", "value": [{"type": "paragraph", "label": "Description", "children": [{"text": "Clear milestones, documented decisions, and close collaboration with the people who operate and maintain the equipment.", "fontSizeOffset": 0, "lineHeightOffset": 0}]}], "layout": {}}]}]}
]
$resume_data$::jsonb AS sections
),
new_resume AS (
    INSERT INTO resumes (user_id, title, styling, layout, created_at, updated_at)
    VALUES (
        1,
        'John Doe - Copper Rail',
        '{"display": "flex", "fontFamily": "Arial, Helvetica, sans-serif", "fontSize": "11.5px", "lineHeight": 1.3, "color": "#30343B", "backgroundColor": "#FFFFFF"}'::json,
        '{"padding": {"top": "1.5rem", "right": "1.5rem", "bottom": "1.5rem", "left": "1.5rem"}, "gap": {"horizontal": "0.3rem", "vertical": "0.4rem", "subsection": "0.6rem", "field": "0.14rem"}}'::json,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
    RETURNING id, title
),
new_columns AS (
    INSERT INTO columns (resume_id, position, styling, layout, created_at, updated_at)
    SELECT r.id, c.position, '{}'::json, c.layout,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM new_resume r
    CROSS JOIN (VALUES
        (0, '{"width": {"auto": false, "value": "29%"}, "padding": {"top": "0rem", "bottom": "0rem", "left": "0.8rem", "right": "0.8rem"}}'::json),
        (1, '{"width": {"auto": false, "value": "71%"}, "padding": {"top": "0rem", "bottom": "0rem", "left": "0.8rem", "right": "0.8rem"}}'::json)
    ) AS c(position, layout)
    RETURNING id, position
),
section_data AS (
    SELECT (s.ordinality - 1)::integer AS position, s.item
    FROM content
    CROSS JOIN LATERAL jsonb_array_elements(content.sections)
        WITH ORDINALITY AS s(item, ordinality)
),
new_sections AS (
    INSERT INTO sections (
        column_id, label, type, value, show_heading, position,
        styling, layout, created_at, updated_at
    )
    SELECT c.id, s.item->>'label', s.item->>'type',
        (s.item->'value')::json,
        (s.item->>'showHeading')::boolean, s.position,
        (s.item->'styling')::json, (s.item->'layout')::json,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM section_data s
    JOIN new_columns c ON c.position = (s.item->>'columnPosition')::integer
    RETURNING id, position
),
subsection_data AS (
    SELECT s.id AS section_id, (sub.ordinality - 1)::integer AS position, sub.item
    FROM new_sections s
    JOIN section_data d ON d.position = s.position
    CROSS JOIN LATERAL jsonb_array_elements(d.item->'subsections')
        WITH ORDINALITY AS sub(item, ordinality)
),
new_subsections AS (
    INSERT INTO subsections (
        section_id, label, type, position, styling, layout, created_at, updated_at
    )
    SELECT d.section_id, d.item->>'label', s.item->>'type', d.position,
        '{"fontSizeOffset":0,"lineHeightOffset":0}'::json, '{}'::json,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM subsection_data d
    JOIN new_sections n ON n.id = d.section_id
    JOIN section_data s ON s.position = n.position
    RETURNING id, section_id, position
),
new_fields AS (
    INSERT INTO fields (
        subsection_id, label, value, position, styling, layout, created_at, updated_at
    )
    SELECT sub.id, f.item->>'label', (f.item->'value')::json,
        (f.ordinality - 1)::integer,
        '{"fontSizeOffset":0,"lineHeightOffset":0}'::json, COALESCE((f.item->'layout')::json, '{}'::json),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM new_subsections sub
    JOIN subsection_data d ON d.section_id = sub.section_id AND d.position = sub.position
    CROSS JOIN LATERAL jsonb_array_elements(d.item->'fields')
        WITH ORDINALITY AS f(item, ordinality)
    RETURNING id
)
SELECT id AS resume_id, title, (SELECT count(*) FROM new_fields) AS fields_created
FROM new_resume;
