"""Add styling column to Column table

Revision ID: 189801fec646
Revises: 284a77b0e055
Create Date: 2026-06-04 17:23:10.783204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189801fec646'
down_revision = '284a77b0e055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('styling', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.drop_column('styling')

    # ### end Alembic commands ###
