"""add plain_text to resumes

Revision ID: 464dc96f6e57
Revises: 8420c4d1927e
Create Date: 2026-09-17 15:43:33.742366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464dc96f6e57'
down_revision = '8420c4d1927e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plain_text', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('plain_text')

    # ### end Alembic commands ###
