"""added layout dictionaries to most tables

Revision ID: 544029a4ec0c
Revises: b4b40718ae3c
Create Date: 2026-05-12 17:05:47.835661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544029a4ec0c'
down_revision = 'b4b40718ae3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('subsections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subsections', schema=None) as batch_op:
        batch_op.drop_column('layout')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('layout')

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('layout')

    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.drop_column('layout')

    # ### end Alembic commands ###
