"""Add source_resume_id column to resumes

Revision ID: 8420c4d1927e
Revises: b14e056ad655
Create Date: 2026-09-16 12:52:26.088177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8420c4d1927e'
down_revision = 'b14e056ad655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_resume_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('source_resume_id')

    # ### end Alembic commands ###
