"""changed ids to integers that autoincrement, and added created_at plus updated_at datetime based columns

Revision ID: b42ff5c7b574
Revises: 6c94da843b81
Create Date: 2026-03-31 11:22:42.241989

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b42ff5c7b574"
down_revision = "6c94da843b81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE fields DROP CONSTRAINT IF EXISTS fk_fields_subsection_id_subsections")
    op.execute("ALTER TABLE sections DROP CONSTRAINT IF EXISTS fk_sections_column_id_columns")
    op.execute("ALTER TABLE subsections DROP CONSTRAINT IF EXISTS fk_subsections_section_id_sections")

    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column(
            'id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using='id::integer'
        )

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column(
            'id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using='id::integer'
        )
        batch_op.alter_column(
            'subsection_id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using='subsection_id::integer'
        )

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column(
            'id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using='id::integer'
        )
        batch_op.alter_column(
            'column_id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using='column_id::integer'
        )

    with op.batch_alter_table('subsections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column(
            'id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using='id::integer'
        )
        batch_op.alter_column(
            'section_id',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using='section_id::integer'
        )

    op.create_foreign_key(
        "fk_fields_subsection_id_subsections",
        "fields",
        "subsections",
        ["subsection_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_sections_column_id_columns",
        "sections",
        "columns",
        ["column_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_subsections_section_id_sections",
        "subsections",
        "sections",
        ["section_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_fields_subsection_id_subsections', 'fields', type_='foreignkey')
    op.drop_constraint('fk_sections_column_id_columns', 'sections', type_='foreignkey')
    op.drop_constraint('fk_subsections_section_id_sections', 'subsections', type_='foreignkey')

    with op.batch_alter_table("subsections", schema=None) as batch_op:
        batch_op.alter_column(
            "section_id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using='section_id::varchar',
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using='id::varchar',
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.alter_column(
            "column_id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using='column_id::varchar',
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using='id::varchar',
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("fields", schema=None) as batch_op:
        batch_op.alter_column(
            "subsection_id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using='subsection_id::varchar',
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using='id::varchar',
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("columns", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using='id::varchar',
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    op.create_foreign_key(
        "fk_fields_subsection_id_subsections",
        "fields",
        "subsections",
        ["subsection_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_sections_column_id_columns",
        "sections",
        "columns",
        ["column_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_subsections_section_id_sections",
        "subsections",
        "sections",
        ["section_id"],
        ["id"],
    )

    # ### end Alembic commands ###
