"""added auto_width to columns table

Revision ID: b4b40718ae3c
Revises: cb6ff410ca2e
Create Date: 2026-05-12 12:29:16.242683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b40718ae3c'
down_revision = 'cb6ff410ca2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_width', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.drop_column('auto_width')

    # ### end Alembic commands ###
