"""added show_heading to sections

Revision ID: cb6ff410ca2e
Revises: b46adf4e04d0
Create Date: 2026-04-30 14:52:05.826351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6ff410ca2e'
down_revision = 'b46adf4e04d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_heading', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('show_heading')

    # ### end Alembic commands ###
