"""removed width and auto_width from columns table

Revision ID: d214adcbd22f
Revises: 2fdf049fa358
Create Date: 2026-05-12 17:16:57.096810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd214adcbd22f'
down_revision = '2fdf049fa358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.drop_column('auto_width')
        batch_op.drop_column('width')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('auto_width', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))

    # ### end Alembic commands ###
